module.exports = {
	navigator: ['push', 'pop'],
	app: ['install', 'uninstall', 'open', 'reboot', 'has'],
	clipboard: ['set', 'get'], // setString
	storage: ['set', 'get', 'remove', 'getAllKeys'], // setItem
	record: ['start', 'stop'],
	audio: ['start', 'stop'],
	video: ['start', 'open'],
	box: ['show', 'hide'],
	photo: ['get', 'save'],
	notification: ['set', 'cancel'],
	system: ['sms', 'mail', 'contacts', 'call'],
	sensor: ['start', 'stop'],
	download: ['start', 'stop'],
	upload: ['start', 'stop'],
	cache: ['get', 'clear'],
	space: ['total', 'free'],
	location: ['start', 'stop', 'get'],
	screen: ['orientate', 'keep', 'home'],
	style: ['win', 'bar', 'badge']
};

// module.exports = [
// 	'push',
// 	'pop',
// 	'setWinAttr',
// 	'installApp',
// 	'uninstallApp',
// 	'openApp',
// 	'appInstalled',
// 	'rebootApp',
// 	'download',
// 	'cancelDownload',
// 	'clearCache',
// 	'getCacheSize',
// 	'getTotalSpace',
// 	'getFreeDiskSpace',
// 	'notification',
// 	'cancelNotification',
// 	'startLocation',
// 	'stopLocation',
// 	'getLocation',
// 	'startSensor',
// 	'stopSensor',
// 	'sms',
// 	'mail',
// 	'call',
// 	'openContacts',
// 	'setStatusBarStyle',
// 	'setScreenOrientation',
// 	'setKeepScreenOn',
// 	'toLauncher',
// 	'setAppIconBadge',
// 	'showFloatBox',
// 	'getPicture',
// 	'saveMediaToAlbum',
// 	'startRecord',
// 	'stopRecord',
// 	'startPlay',
// 	'stopPlay',
// 	'openVideo',
// 	'require'
// ];